version: '2.4'
services:
  app:
    build: .
    image: internship_qualifier
    mem_reservation: "1024m"
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/service

  mongo:
    image: mongo:4.4.5
    restart: always
    expose:
      - 27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongo
